---
- name: Prepare
  hosts: all
  tasks:
  - name: Install Dependencies
    become: true
    ansible.builtin.apt:
      name: curl
      update_cache: true
      state: present
    when: >
      ansible_distribution == "Ubuntu"
      or ansible_distribution == "Debian"
      or ansible_distribution == "Pop!_OS"

  - name: Install Dependencies
    become: true
    ansible.builtin.yum:
      name: curl
      state: present
    when: >
      ansible_distribution == "Amazon"
      or ansible_distribution == "CentOS"
