---
- name: Verify
  hosts: all
  gather_facts: false
  tasks:
  - name: Projector executable exists
    ansible.builtin.command:
      cmd: which projector
    changed_when: false
    register: which_projector

  - name: Assertions
    ansible.builtin.assert:
      that:
        - which_projector.rc == 0
        - which_projector.stdout == "/usr/local/bin/projector"

  - name: Test IDEs
    ansible.builtin.uri:
      url: http://127.0.0.1:{{ item }}/
      status_code: 200
    loop:
      - 9000

  - name: Test uninstallation  # noqa command-instead-of-module
    ansible.builtin.command:
      cmd: curl http://127.0.0.1:{{ item }}/
    register: uninstall_cmd
    changed_when: false
    failed_when: uninstall_cmd.rc != 7
    loop:
      - 9876
