- name: Yum Cache Update
  become: true
  ansible.builtin.yum:
    update_cache: true
  changed_when: false

- name: Install Dependencies
  become: true
  ansible.builtin.yum:
    name: '{{ yum_dependencies + centos7_dependencies }}'
    state: present
  when: >
    (ansible_distribution == 'CentOS' and ansible_distribution_major_version < '8')
    or ansible_distribution == 'Amazon'

- name: Install Dependencies
  become: true
  ansible.builtin.yum:
    name: '{{ yum_dependencies + centos_modern_dependencies }}'
    state: present
  when: >
    ansible_distribution == 'CentOS' and ansible_distribution_major_version >= '8'
