- name: Yum Cache Update
  become: true
  ansible.builtin.yum:
    update_cache: true
  changed_when: false

- name: Older CentOS families
  when: >
    (ansible_distribution == 'CentOS' and ansible_distribution_major_version < '8')
    or ansible_distribution == 'Amazon'
  block:
    - name: Install Dependencies
      become: true
      ansible.builtin.yum:
        name: '{{ yum_dependencies + centos7_dependencies }}'
        state: present

    - name: Install Pip Dependencies
      ansible.builtin.pip:
        name: pexpect

- name: Install Dependencies
  become: true
  ansible.builtin.yum:
    name: '{{ yum_dependencies + centos_modern_dependencies }}'
    state: present
  when: >
    ansible_distribution == 'CentOS' and ansible_distribution_major_version >= '8'
