- name: Operating System
  ansible.builtin.debug:
    msg: "{{ ansible_distribution }} {{ ansible_distribution_major_version }} ({{ ansible_distribution_release }})"

- name: Debian and related families
  when: ansible_distribution in debian_family
  include_tasks: debian.yml

- name: Ensure pip is up-to-date
  changed_when: false
  ansible.builtin.command:
    cmd: python3 -m pip install -U pip

- name: Install Projector
  ansible.builtin.pip:
    name: projector-installer
    executable: /usr/local/bin/pip3
