---
- name: Converge
  hosts: all
  tasks:
    - name: "Include artis3n.jetbrains_projector"
      ansible.builtin.include_role:
        name: "artis3n.jetbrains_projector"
      vars:
        ides:
          - name: WebStorm 2021.2.3
            port: 9876

          - name: GoLand 2021.2.4
            port: 9999
            config: mygoland
            address: 127.0.0.1
            restricted_access_hostnames: 127.0.0.1
            required_connection_password: mypass
