---
- name: Verify
  hosts: all
  gather_facts: false
  tasks:
  - name: Projector executable exists
    ansible.builtin.command:
      cmd: which projector
    changed_when: false
    register: which_projector

  - name: Assertions
    ansible.builtin.assert:
      that:
        - which_projector.rc == 0
        - which_projector.stdout == "/usr/local/bin/projector"

  - name: Test systemd services
    ansible.builtin.systemd:
      name: "{{ item }}.service"
      state: started
    loop:
      - WebStorm
      - GoLand

  - name: Test IDEs
    ansible.builtin.uri:
      url: http://127.0.0.1:{{ item }}/
      status_code: 200
    loop:
      - 9876
      - 9999
