---
name: CI Tests

on:
  pull_request:
    branches:
      - main

jobs:
  molecule:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        distros:
          - ghcr.io/artis3n/docker-ubuntu2104-ansible:latest
          #  20.10 is EOL
          # apt update: "The repository 'http://archive.ubuntu.com/ubuntu groovy Release' does not have a Release file"
          # - ghcr.io/artis3n/docker-ubuntu2010-ansible:latest
          - geerlingguy/docker-ubuntu2004-ansible:latest
          - geerlingguy/docker-rockylinux8-ansible:latest
          - ghcr.io/artis3n/docker-almalinux8-ansible:latest
          - geerlingguy/docker-centos8-ansible:latest
          # Python 3 sucks on Centos 7, and is a requirement for this role.
          # We'll continue to support Centos 7 if issues are reported to the repo.
          # - geerlingguy/docker-centos7-ansible:python3
          - ghcr.io/artis3n/docker-amazonlinux2-ansible:latest
          - ghcr.io/artis3n/docker-debian11-ansible:latest
          - geerlingguy/docker-debian10-ansible:latest
      fail-fast: false

    steps:
      - uses: actions/checkout@v3

      # - name: Install dependency manager
      #   run: pipx install poetry

      - name: Set up Python
        id: setup-python
        uses: actions/setup-python@v3.1.2
        with:
          python-version: "3.10"
          # Once supported in https://github.com/actions/setup-python/pull/281
          # cache: 'poetry'

      - name: Install dependency manager
        # https://python-poetry.org/docs/master/#installing-with-the-official-installer
        run: curl -sSL https://install.python-poetry.org | python3 -

      - name: Install Packages
        run: poetry install --no-interaction

      - name: Molecule
        run: poetry run molecule test --all --parallel
        env:
          MOLECULE_DISTRO: ${{ matrix.distros }}
          # https://www.jeffgeerling.com/blog/2020/getting-colorized-output-molecule-and-ansible-on-github-actions-ci
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
