name: CI Tests

on:
  pull_request:
    branches:
      - main

jobs:
  molecule:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        distros:
          - ghcr.io/artis3n/docker-ubuntu2104-ansible:latest
          - ghcr.io/artis3n/docker-ubuntu2010-ansible:latest
          - geerlingguy/docker-ubuntu2004-ansible:latest
          - geerlingguy/docker-centos8-ansible:latest
          - geerlingguy/docker-centos7-ansible:latest
          - geerlingguy/docker-amazonlinux2-ansible:latest
          - ghcr.io/artis3n/docker-debian11-ansible:latest
          - geerlingguy/docker-debian10-ansible:latest
      fail-fast: false

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pipenv

      - name: Use Cache
        uses: actions/cache@v2.1.6
        with:
          path: ~/.local/share/virtualenvs
          key: ${{ runner.os }}-pipenv-${{ hashFiles('Pipfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pipenv-

      - name: Install Packages
        run: pipenv install --dev

      - name: Lint
        run: make lint

      - name: Molecule
        run: pipenv run molecule test
        env:
          MOLECULE_DISTRO: ${{ matrix.distros }}
